# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teliverdemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for teliverdemo
  pod ‘IQKeyboardManagerSwift’
  pod 'Toast-Swift', '~> 3.0.1'
end
